#ifndef BATTLE_TYPES_H
#define BATTLE_TYPES_H

typedef enum {
    DIALOGUE_BATTLE_0,
    DIALOGUE_BATTLE_1,
    DIALOGUE_BATTLE_2,
    DIALOGUE_BATTLE_3,
    DIALOGUE_BATTLE_4,
    DIALOGUE_BATTLE_FINAL_INTRO,
    DIALOGUE_BATTLE_5,
    DIALOGUE_AFTER_TRASH_TALK,
    DIALOGUE_BATTLE_6,
    DIALOGUE_BATTLE_7,
    DIALOGUE_BATTLE_8,
    DIALOGUE_BATTLE_9,
    DIALOGUE_BATTLE_10
} Dialogues;

typedef enum{
    BATTLE_DIALOGUE,
    BATTLE_START,
    BATTLE_WIN,
    BATTLE_LOST,
    BATTLE_END,
    BATTLE_NONE
} Battle_state;

#endif