#ifndef BATTLE_TYPES_H
#define BATTLE_TYPES_H

typedef enum {
    DIALOGUE_BATTLE_0,
    DIALOGUE_BATTLE_1,
    DIALOGUE_BATTLE_2,
    DIALOGUE_BATTLE_3,
    DIALOGUE_BATTLE_4,
    DIALOGUE_BATTLE_5,
    DIALOGUE_BATTLE_6,
    DIALOGUE_BATTLE_7,
    DIALOGUE_BATTLE_8,
    DIALOGUE_BATTLE_9,
    DIALOGUE_BATTLE_10,
    DIALOGUE_MEDUSA_1,
    DIALOGUE_MEDUSA_2,
    DIALOGUE_MEDUSA_3,
    DIALOGUE_MEDUSA_4,
    DIALOGUE_MEDUSA_5,
    DIALOGUE_MEDUSA_FINAL_1,
    DIALOGUE_MEDUSA_FINAL_2,
    DIALOGUE_MEDUSA_FINAL_3,
    DIALOGUE_MEDUSA_RANDOM_1,
    DIALOGUE_MEDUSA_RANDOM_2,
    DIALOGUE_MEDUSA_RANDOM_3,
    DIALOGUE_ARAUTO_1,
    DIALOGUE_ARAUTO_2,
    DIALOGUE_ARAUTO_3,
    DIALOGUE_ARAUTO_4,
    DIALOGUE_ARAUTO_5,
    DIALOGUE_ARAUTO_FINAL_1,
    DIALOGUE_ARAUTO_FINAL_2,
    DIALOGUE_ARAUTO_FINAL_3,
    DIALOGUE_ARAUTO_FINAL_4,
    DIALOGUE_ARAUTO_FINAL_5,
    DIALOGUE_ARAUTO_RANDOM_1,
    DIALOGUE_ARAUTO_RANDOM_2,
    DIALOGUE_ARAUTO_RANDOM_3,
    DIALOGUE_BATTLE_FINAL_INTRO,
    DIALOGUE_AFTER_TRASH_TALK
} Dialogues;

typedef enum{
    BATTLE_DIALOGUE,
    BATTLE_START,
    BATTLE_WIN,
    BATTLE_LOST,
    BATTLE_END,
    BATTLE_NONE
} Battle_state;

#endif