#ifndef GAME_STATE_H
#define GAME_STATE_H

typedef enum{
    GAME_MENU,
    GAME_PAUSE,
    GAME_TUTORIAL,
    GAME_INIT,
    GAME_MINOTAUR_LEVEL,
    GAME_MEDUSA_LEVEL,
    GAME_ARAUTO_LEVEL,
    GAME_FIRST_MISSION,
    GAME_SECOND_MISSION,
    GAME_THIRD_MISSION,
    GAME_BATTLE,
    GAME_PUZZLE_SCREEN,
    GAME_OVER,
    GAME_END
} Game_state;

#endif